/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BarangController;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author saniaasrimonica
 */
public class FormBarang extends javax.swing.JFrame {

    /**
     * Creates new form FormBarang
     */
    BarangController barangController;
    public FormBarang() {
        initComponents();
        barangController = new BarangController(this);
        barangController.tampilTabel();
        barangController.bersihForm();
        txtKodeBarang.setText(getTxtProdukBarang().getText() + getTxtGrupBarang().getText());
        
    }

    public JTextField getTxtGrupBarang() {
        return txtGrupBarang;
    }

    public void setTxtGrupBarang(JTextField txtGrupBarang) {
        this.txtGrupBarang = txtGrupBarang;
    }

    public JTextField getTxtProdukBarang() {
        return txtProdukBarang;
    }

    public void setTxtProdukBarang(JTextField txtProdukBarang) {
        this.txtProdukBarang = txtProdukBarang;
    }

    public JComboBox<String> getCmbSatuan() {
        return CmbSatuan;
    }

    public void setCmbSatuan(JComboBox<String> CmbSatuan) {
        this.CmbSatuan = CmbSatuan;
    }

    public JTextField getTxtKodeBarang() {
        return txtKodeBarang;
    }

    public void setTxtKodeBarang(JTextField txtKodeBarang) {
        this.txtKodeBarang = txtKodeBarang;
    }

    public JTable getTabelBarang() {
        return tabelBarang;
    }

    public void setTabelBarang(JTable tabelBarang) {
        this.tabelBarang = tabelBarang;
    }

    public JTextField getTxtHargaBeli() {
        return txtHargaBeli;
    }

    public void setTxtHargaBeli(JTextField txtHargaBeli) {
        this.txtHargaBeli = txtHargaBeli;
    }

    public JTextField getTxtHargaJual() {
        return txtHargaJual;
    }

    public void setTxtHargaJual(JTextField txtHargaJual) {
        this.txtHargaJual = txtHargaJual;
    }

    public JTextField getTxtNamaBarang() {
        return txtNamaBarang;
    }

    public void setTxtNamaBarang(JTextField txtNamaBarang) {
        this.txtNamaBarang = txtNamaBarang;
    }

    public JTextField getTxtStokBarang() {
        return txtStokBarang;
    }

    public void setTxtStokBarang(JTextField txtStokBarang) {
        this.txtStokBarang = txtStokBarang;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        txtHargaBeli = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        txtStokBarang = new javax.swing.JTextField();
        CmbSatuan = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnInsert1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtKodeBarang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGrupBarang = new javax.swing.JTextField();
        txtProdukBarang = new javax.swing.JTextField();
        btnGrupBarang = new javax.swing.JButton();
        btnProdukBarang = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Kode Grup");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 80, 14);

        jLabel2.setText("Kode produk");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 90, 14);

        jLabel3.setText("Nama Barang");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 100, 14);

        jLabel4.setText("Satuan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 190, 70, 14);

        jLabel5.setText("Harga Beli");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 230, 80, 14);

        jLabel6.setText("Harga Jual");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 260, 80, 14);

        jLabel7.setText("Stok Barang");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 290, 90, 14);

        txtNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaBarang);
        txtNamaBarang.setBounds(140, 140, 215, 30);

        txtHargaBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaBeliActionPerformed(evt);
            }
        });
        getContentPane().add(txtHargaBeli);
        txtHargaBeli.setBounds(140, 220, 135, 30);

        txtHargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaJualActionPerformed(evt);
            }
        });
        getContentPane().add(txtHargaJual);
        txtHargaJual.setBounds(140, 250, 135, 30);
        getContentPane().add(txtStokBarang);
        txtStokBarang.setBounds(140, 280, 135, 30);

        CmbSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tablet", "pcs" }));
        getContentPane().add(CmbSatuan);
        CmbSatuan.setBounds(140, 180, 130, 30);

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Produk", "Kode Grup", "Kode Barang", "Nama Barang", "Satuan ", "Haraga Beli[Rp]", "Haraga Jual[Rp]", "Stok Barang"
            }
        ));
        jScrollPane2.setViewportView(tabelBarang);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 420, 511, 191);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 370, 57, 20);

        btnInsert1.setText("Insert");
        btnInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert1);
        btnInsert1.setBounds(51, 365, 61, 23);

        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate1);
        btnUpdate1.setBounds(153, 365, 67, 23);

        btnDelete1.setText("Delete");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete1);
        btnDelete1.setBounds(264, 365, 63, 23);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(53, 86, 0, 0);
        getContentPane().add(txtKodeBarang);
        txtKodeBarang.setBounds(140, 110, 215, 30);

        jLabel9.setText("Kode Barang");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 110, 90, 14);

        txtGrupBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrupBarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtGrupBarang);
        txtGrupBarang.setBounds(140, 20, 71, 30);

        txtProdukBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdukBarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtProdukBarang);
        txtProdukBarang.setBounds(140, 60, 71, 30);

        btnGrupBarang.setText("jButton2");
        btnGrupBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupBarangActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrupBarang);
        btnGrupBarang.setBounds(230, 20, 39, 23);

        btnProdukBarang.setText("jButton3");
        btnProdukBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukBarangActionPerformed(evt);
            }
        });
        getContentPane().add(btnProdukBarang);
        btnProdukBarang.setBounds(230, 60, 39, 23);

        jButton3.setText("Cari");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(370, 110, 73, 30);

        setSize(new java.awt.Dimension(537, 698));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      barangController.bersihForm();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert1ActionPerformed
       barangController.insert();
       barangController.bersihForm();
       barangController.tampilTabel();        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsert1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
       barangController.update();
       barangController.bersihForm();
       barangController.tampilTabel();   // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
       barangController.delete();
       barangController.bersihForm();
       barangController.tampilTabel();        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void txtHargaBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaBeliActionPerformed

    private void btnProdukBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukBarangActionPerformed
        // TODO add your handling code here:
        if(txtGrupBarang.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Isikan Grub Barang Terlebih Dahulu");
        }else{
        DialogProduk dialogPegawai = new DialogProduk(this, true);
        dialogPegawai.setVisible(true);
        barangController.getKodebarang();
        }
        
    }//GEN-LAST:event_btnProdukBarangActionPerformed

    private void btnGrupBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupBarangActionPerformed
        // TODO add your handling code here:
        
        DialogGrup dialogPegawai = new DialogGrup(this, true);
        dialogPegawai.setVisible(true);
        
    }//GEN-LAST:event_btnGrupBarangActionPerformed

    private void txtNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBarangActionPerformed

    private void txtHargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaJualActionPerformed

    private void txtProdukBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdukBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdukBarangActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        barangController.cariData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtGrupBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrupBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrupBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbSatuan;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnGrupBarang;
    private javax.swing.JButton btnInsert1;
    private javax.swing.JButton btnProdukBarang;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JTextField txtGrupBarang;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtProdukBarang;
    private javax.swing.JTextField txtStokBarang;
    // End of variables declaration//GEN-END:variables
}
