/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author saniaasrimonica
 */
public class FormMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form FromMenuUtama
     */
    public FormMenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuPengguna = new javax.swing.JMenuItem();
        MenuBarang = new javax.swing.JMenuItem();
        MenuProduk = new javax.swing.JMenuItem();
        MenuGrup = new javax.swing.JMenuItem();
        MenuPelanggan = new javax.swing.JMenuItem();
        MenuPemasok = new javax.swing.JMenuItem();
        Menu2 = new javax.swing.JMenu();
        MenuPenjualan = new javax.swing.JMenuItem();
        MenuPembelian = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Input");

        MenuPengguna.setText("Data Pengguna");
        MenuPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPenggunaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuPengguna);

        MenuBarang.setText("Data Barang");
        MenuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarangActionPerformed(evt);
            }
        });
        jMenu1.add(MenuBarang);

        MenuProduk.setText("Data Produk");
        MenuProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProdukActionPerformed(evt);
            }
        });
        jMenu1.add(MenuProduk);

        MenuGrup.setText("Data Grup");
        MenuGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGrupActionPerformed(evt);
            }
        });
        jMenu1.add(MenuGrup);

        MenuPelanggan.setText("Data Pelanggan");
        MenuPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPelangganActionPerformed(evt);
            }
        });
        jMenu1.add(MenuPelanggan);

        MenuPemasok.setText("Data Pemasok");
        MenuPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPemasokActionPerformed(evt);
            }
        });
        jMenu1.add(MenuPemasok);

        jMenuBar1.add(jMenu1);

        Menu2.setText("Transaksi");

        MenuPenjualan.setText("Penjualan ");
        MenuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPenjualanActionPerformed(evt);
            }
        });
        Menu2.add(MenuPenjualan);

        MenuPembelian.setText("Pembelian");
        MenuPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPembelianActionPerformed(evt);
            }
        });
        Menu2.add(MenuPembelian);

        jMenuBar1.add(Menu2);

        jMenu3.setText("Laporan");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Login");

        jMenuItem1.setText("Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    FormLogin login=new FormLogin();
    login.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPenggunaActionPerformed
        // TODO add your handling code here:
        FormPengguna pengguna = new FormPengguna();
        pengguna.setVisible(true);
    }//GEN-LAST:event_MenuPenggunaActionPerformed

    private void MenuGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGrupActionPerformed
    FormGrupBarang grupBarang = new FormGrupBarang();
    grupBarang.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_MenuGrupActionPerformed

    private void MenuPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPemasokActionPerformed
    FormPemasok pemasok = new FormPemasok();
    pemasok.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_MenuPemasokActionPerformed

    private void MenuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarangActionPerformed
        // TODO add your handling code here:
        FormBarang barang = new FormBarang();
        barang.setVisible(true);
    }//GEN-LAST:event_MenuBarangActionPerformed

    private void MenuProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProdukActionPerformed
        FormProduk produk =new FormProduk();
        produk.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_MenuProdukActionPerformed

    private void MenuPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPelangganActionPerformed
        FormPelanggan pelanggan = new FormPelanggan();
        pelanggan.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPelangganActionPerformed

    private void MenuPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPembelianActionPerformed
    FormPembelian pembelian = new FormPembelian();
    pembelian.setVisible(true);
      // TODO add your handling code here:
    }//GEN-LAST:event_MenuPembelianActionPerformed

    private void MenuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPenjualanActionPerformed
    FormPenjualan penjualan = new FormPenjualan();
    penjualan.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_MenuPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu2;
    private javax.swing.JMenuItem MenuBarang;
    private javax.swing.JMenuItem MenuGrup;
    private javax.swing.JMenuItem MenuPelanggan;
    private javax.swing.JMenuItem MenuPemasok;
    private javax.swing.JMenuItem MenuPembelian;
    private javax.swing.JMenuItem MenuPengguna;
    private javax.swing.JMenuItem MenuPenjualan;
    private javax.swing.JMenuItem MenuProduk;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
